Profiles:
  delphiGenesis:
    Capabilities:
      V1_1: true
    Orderer:
      BatchTimeout: 1s
      BatchSize:
        MaxMessageCount: 1
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Capabilities:
        V1_1: true
      OrdererType: solo
      Addresses:
        - 'orderer.Delphi.com:7050'
      Organizations:
        - Name: OrdererMSPName
          ID: OrdererMSP
          MSPDir: /home/blockchain/Documents/delphi-fabric/config/ca-crypto-config/ordererOrganizations/Delphi.com/msp
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: ASTRIMSPName
            ID: ASTRIMSP
            MSPDir: /home/blockchain/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.org/msp
            AnchorPeers:
              - Host: peer0.ASTRI.org
                Port: 7051
  allchannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: ASTRIMSPName
          ID: ASTRIMSP
          MSPDir: /home/blockchain/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.org/msp
          AnchorPeers:
            - Host: peer0.ASTRI.org
              Port: 7051
      Capabilities:
        V1_2: true
