Profiles:
  delphiGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
        - 'orderContainerName:7050'
      BatchTimeout: 1s
      BatchSize:
        MaxMessageCount: 1
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Organizations:
        - Name: OrdererMSPName
          ID: OrdererMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/ordererOrganizations/Delphi.com/msp
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: BUMSPName
            ID: BUMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/BU.Delphi.com/msp
            AnchorPeers:
              - Host: bu
                Port: 7051
          - Name: PMMSPName
            ID: PMMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/PM.Delphi.com/msp
            AnchorPeers:
              - Host: pm
                Port: 7051
          - Name: ENGMSPName
            ID: ENGMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ENG.Delphi.com/msp
            AnchorPeers:
              - Host: eng
                Port: 7051
          - Name: ASTRIMSPName
            ID: ASTRIMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.Delphi.com/msp
            AnchorPeers:
              - Host: astri
                Port: 7051
  allChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: BUMSPName
          ID: BUMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/BU.Delphi.com/msp
          AnchorPeers:
            - Host: bu
              Port: 7051
        - Name: PMMSPName
          ID: PMMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/PM.Delphi.com/msp
          AnchorPeers:
            - Host: pm
              Port: 7051
        - Name: ENGMSPName
          ID: ENGMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ENG.Delphi.com/msp
          AnchorPeers:
            - Host: eng
              Port: 7051
        - Name: ASTRIMSPName
          ID: ASTRIMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.Delphi.com/msp
          AnchorPeers:
            - Host: astri
              Port: 7051
