Profiles:
  tradeGenesis:
    Orderer:
      BatchTimeout: 1s
      BatchSize:
        MaxMessageCount: 1
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      OrdererType: solo
      Addresses:
        - 'orderContainerName.astri.org:7050'
      Organizations:
        - Name: OrdererMSPName
          ID: OrdererMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/ordererOrganizations/astri.org/msp
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: Consumer
            ID: ConsumerMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/Consumer/msp
            AnchorPeers:
              - Host: peer0.Consumer
                Port: 7051
          - Name: Merchant
            ID: MerchantMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/Merchant/msp
            AnchorPeers:
              - Host: peer0.Merchant
                Port: 7051
          - Name: Exchange
            ID: ExchangeMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/Exchange/msp
            AnchorPeers:
              - Host: peer0.Exchange
                Port: 7051
  allchannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: Consumer
          ID: ConsumerMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/Consumer/msp
          AnchorPeers:
            - Host: peer0.Consumer
              Port: 7051
        - Name: Merchant
          ID: MerchantMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/Merchant/msp
          AnchorPeers:
            - Host: peer0.Merchant
              Port: 7051
        - Name: Exchange
          ID: ExchangeMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/Exchange/msp
          AnchorPeers:
            - Host: peer0.Exchange
              Port: 7051
