Profiles:
  delphiGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
        - 'orderContainerName:7050'
      BatchTimeout: 10s
      BatchSize:
        MaxMessageCount: 3000
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 10 MB
      Organizations:
        - Name: OrdererMSPName
          ID: OrdererMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/ordererOrganizations/Delphi.com/msp
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: BUMSPName
            ID: BUMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/BU.Delphi.com/msp
            AnchorPeers:
              - Host: BUContainerName
                Port: 7051
          - Name: ENGMSPName
            ID: ENGMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/ENG.Delphi.com/msp
            AnchorPeers:
              - Host: ENGContainerName
                Port: 7051
          - Name: PMMSPName
            ID: PMMSP
            MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/PM.Delphi.com/msp
            AnchorPeers:
              - Host: PMContainerName
                Port: 7051
  delphiChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: BUMSPName
          ID: BUMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/BU.Delphi.com/msp
          AnchorPeers:
            - Host: BUContainerName
              Port: 7051
        - Name: PMMSPName
          ID: PMMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/PM.Delphi.com/msp
          AnchorPeers:
            - Host: PMContainerName
              Port: 7051
        - Name: ENGMSPName
          ID: ENGMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/ENG.Delphi.com/msp
          AnchorPeers:
            - Host: ENGContainerName
              Port: 7051
  BUChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: BUMSPName
          ID: BUMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/BU.Delphi.com/msp
          AnchorPeers:
            - Host: BUContainerName
              Port: 7051
