PeerOrgs:
  - Domain: SUPPLY.Teeking.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
  - Domain: CAR.Teeking.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
  - Domain: FACTORY.Teeking.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
  - Domain: TK.Teeking.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
OrdererOrgs:
  - Domain: Teeking.com
    Specs:
      - Hostname: orderContainerName
