PeerOrgs:
  - Domain: BU.Delphi.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
  - Domain: PM.Delphi.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
  - Domain: ENG.Delphi.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
  - Domain: ASTRI.Delphi.com
    Template:
      Start: 0
      Count: 1
    Users:
      Count: 0
OrdererOrgs:
  - Domain: Delphi.com
    Specs:
      - Hostname: orderContainerName
