version: '3'
volumes:
  MSPROOT_local:
    external: true
  CONFIGTX_local:
    external: true
networks:
  default:
    external:
      name: delphiNetwork
services:
  peer0.BU.Delphi.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.BU.Delphi.com:7051'
      - CORE_PEER_LOCALMSPID=BUMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer0.BU.Delphi.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.BU.Delphi.com
      - 'CORE_PEER_ADDRESS=peer0.BU.Delphi.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052'
      - GODEBUG=netdns=go
    ports:
      - '6051:7051'
      - '6053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderContainerName
    container_name: bu
    networks:
      - default
  peer0.PM.Delphi.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.PM.Delphi.com:7051'
      - CORE_PEER_LOCALMSPID=PMMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/PM.Delphi.com/peers/peer0.PM.Delphi.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.PM.Delphi.com
      - 'CORE_PEER_ADDRESS=peer0.PM.Delphi.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052'
      - GODEBUG=netdns=go
    ports:
      - '8051:7051'
      - '8053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderContainerName
    container_name: pm
    networks:
      - default
  peer0.ENG.Delphi.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ENG.Delphi.com:7051'
      - CORE_PEER_LOCALMSPID=ENGMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/ENG.Delphi.com/peers/peer0.ENG.Delphi.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.ENG.Delphi.com
      - 'CORE_PEER_ADDRESS=peer0.ENG.Delphi.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052'
      - GODEBUG=netdns=go
    ports:
      - '9051:7051'
      - '9053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderContainerName
    container_name: eng
    networks:
      - default
  peer0.ASTRI.Delphi.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ASTRI.Delphi.com:7051'
      - CORE_PEER_LOCALMSPID=ASTRIMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/ASTRI.Delphi.com/peers/peer0.ASTRI.Delphi.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.ASTRI.Delphi.com
      - 'CORE_PEER_ADDRESS=peer0.ASTRI.Delphi.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052'
      - GODEBUG=netdns=go
    ports:
      - '7051:7051'
      - '7053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderContainerName
    container_name: astri
    networks:
      - default
  orderContainerName:
    image: 'hyperledger/fabric-orderer:x86_64-1.1.0'
    command: orderer
    ports:
      - '7050:7050'
    volumes:
      - 'CONFIGTX_local:/etc/hyperledger/configtx'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/delphi.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/msp
      - GODEBUG=netdns=go
    networks:
      default:
        aliases:
          - orderContainerName
    container_name: orderContainerName
